// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// probe_xad_xtensor
int probe_xad_xtensor();
RcppExport SEXP _xopt_probe_xad_xtensor() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(probe_xad_xtensor());
    return rcpp_result_gen;
END_RCPP
}

// probe_sdm
int probe_sdm();
RcppExport SEXP _xopt_probe_sdm() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(probe_sdm());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_xopt_probe_xad_xtensor", (DL_FUNC) &_xopt_probe_xad_xtensor, 0},
    {"_xopt_probe_sdm", (DL_FUNC) &_xopt_probe_sdm, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_xopt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
