// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// probe_xad_xtensor
int probe_xad_xtensor();
RcppExport SEXP _xopt_probe_xad_xtensor() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(probe_xad_xtensor());
    return rcpp_result_gen;
END_RCPP
}
// xopt_implicit_spd_grad_ridge
double xopt_implicit_spd_grad_ridge(Rcpp::NumericMatrix X, Rcpp::NumericVector y, double lambda);
RcppExport SEXP _xopt_xopt_implicit_spd_grad_ridge(SEXP XSEXP, SEXP ySEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_implicit_spd_grad_ridge(X, y, lambda));
    return rcpp_result_gen;
END_RCPP
}
// xopt_implicit_spd_grad_generic
Rcpp::NumericVector xopt_implicit_spd_grad_generic(Rcpp::NumericMatrix A, Rcpp::NumericMatrix B, Rcpp::NumericVector x_star, Rcpp::NumericVector x_bar);
RcppExport SEXP _xopt_xopt_implicit_spd_grad_generic(SEXP ASEXP, SEXP BSEXP, SEXP x_starSEXP, SEXP x_barSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_star(x_starSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_bar(x_barSEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_implicit_spd_grad_generic(A, B, x_star, x_bar));
    return rcpp_result_gen;
END_RCPP
}
// xopt_chol_impl
Rcpp::NumericMatrix xopt_chol_impl(Rcpp::NumericMatrix A);
RcppExport SEXP _xopt_xopt_chol_impl(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_chol_impl(A));
    return rcpp_result_gen;
END_RCPP
}
// xopt_solve_impl
Rcpp::NumericVector xopt_solve_impl(Rcpp::NumericMatrix A, Rcpp::NumericVector b);
RcppExport SEXP _xopt_xopt_solve_impl(SEXP ASEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_solve_impl(A, b));
    return rcpp_result_gen;
END_RCPP
}
// xopt_logdet_impl
double xopt_logdet_impl(Rcpp::NumericMatrix A);
RcppExport SEXP _xopt_xopt_logdet_impl(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_logdet_impl(A));
    return rcpp_result_gen;
END_RCPP
}
// xopt_inv_impl
Rcpp::NumericMatrix xopt_inv_impl(Rcpp::NumericMatrix A);
RcppExport SEXP _xopt_xopt_inv_impl(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_inv_impl(A));
    return rcpp_result_gen;
END_RCPP
}
// xopt_chol_grad
Rcpp::NumericMatrix xopt_chol_grad(Rcpp::NumericMatrix A);
RcppExport SEXP _xopt_xopt_chol_grad(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_chol_grad(A));
    return rcpp_result_gen;
END_RCPP
}
// xopt_solve_grad
SEXP xopt_solve_grad(Rcpp::NumericMatrix A, Rcpp::NumericVector b, std::string wrt);
RcppExport SEXP _xopt_xopt_solve_grad(SEXP ASEXP, SEXP bSEXP, SEXP wrtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< std::string >::type wrt(wrtSEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_solve_grad(A, b, wrt));
    return rcpp_result_gen;
END_RCPP
}
// xopt_logdet_grad
Rcpp::NumericMatrix xopt_logdet_grad(Rcpp::NumericMatrix A);
RcppExport SEXP _xopt_xopt_logdet_grad(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_logdet_grad(A));
    return rcpp_result_gen;
END_RCPP
}
// xopt_inv_grad
Rcpp::NumericMatrix xopt_inv_grad(Rcpp::NumericMatrix A);
RcppExport SEXP _xopt_xopt_inv_grad(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_inv_grad(A));
    return rcpp_result_gen;
END_RCPP
}
// xopt_linalg_tape_bytes
double xopt_linalg_tape_bytes(Rcpp::NumericMatrix A, std::string op);
RcppExport SEXP _xopt_xopt_linalg_tape_bytes(SEXP ASEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< std::string >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_linalg_tape_bytes(A, op));
    return rcpp_result_gen;
END_RCPP
}
// xopt_internal_run_test
int xopt_internal_run_test(std::string name);
RcppExport SEXP _xopt_xopt_internal_run_test(SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_internal_run_test(name));
    return rcpp_result_gen;
END_RCPP
}
// xopt_tr_newton_cpp
Rcpp::List xopt_tr_newton_cpp(Rcpp::NumericVector par, Rcpp::Function fn, Rcpp::Nullable<Rcpp::Function> gr, Rcpp::Nullable<Rcpp::Function> hvp, Rcpp::List control);
RcppExport SEXP _xopt_xopt_tr_newton_cpp(SEXP parSEXP, SEXP fnSEXP, SEXP grSEXP, SEXP hvpSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type fn(fnSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::Function> >::type gr(grSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::Function> >::type hvp(hvpSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_tr_newton_cpp(par, fn, gr, hvp, control));
    return rcpp_result_gen;
END_RCPP
}
// xopt_nls_cpp
Rcpp::List xopt_nls_cpp(Rcpp::NumericVector par, Rcpp::Function residual_fn, Rcpp::Nullable<Rcpp::Function> jacobian_fn, Rcpp::List control);
RcppExport SEXP _xopt_xopt_nls_cpp(SEXP parSEXP, SEXP residual_fnSEXP, SEXP jacobian_fnSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type residual_fn(residual_fnSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::Function> >::type jacobian_fn(jacobian_fnSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_nls_cpp(par, residual_fn, jacobian_fn, control));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_xopt_probe_xad_xtensor", (DL_FUNC) &_xopt_probe_xad_xtensor, 0},
    {"_xopt_xopt_implicit_spd_grad_ridge", (DL_FUNC) &_xopt_xopt_implicit_spd_grad_ridge, 3},
    {"_xopt_xopt_implicit_spd_grad_generic", (DL_FUNC) &_xopt_xopt_implicit_spd_grad_generic, 4},
    {"_xopt_xopt_chol_impl", (DL_FUNC) &_xopt_xopt_chol_impl, 1},
    {"_xopt_xopt_solve_impl", (DL_FUNC) &_xopt_xopt_solve_impl, 2},
    {"_xopt_xopt_logdet_impl", (DL_FUNC) &_xopt_xopt_logdet_impl, 1},
    {"_xopt_xopt_inv_impl", (DL_FUNC) &_xopt_xopt_inv_impl, 1},
    {"_xopt_xopt_chol_grad", (DL_FUNC) &_xopt_xopt_chol_grad, 1},
    {"_xopt_xopt_solve_grad", (DL_FUNC) &_xopt_xopt_solve_grad, 3},
    {"_xopt_xopt_logdet_grad", (DL_FUNC) &_xopt_xopt_logdet_grad, 1},
    {"_xopt_xopt_inv_grad", (DL_FUNC) &_xopt_xopt_inv_grad, 1},
    {"_xopt_xopt_linalg_tape_bytes", (DL_FUNC) &_xopt_xopt_linalg_tape_bytes, 2},
    {"_xopt_xopt_internal_run_test", (DL_FUNC) &_xopt_xopt_internal_run_test, 1},
    {"_xopt_xopt_tr_newton_cpp", (DL_FUNC) &_xopt_xopt_tr_newton_cpp, 5},
    {"_xopt_xopt_nls_cpp", (DL_FUNC) &_xopt_xopt_nls_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_xopt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
