// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// probe_xad_xtensor
int probe_xad_xtensor();
RcppExport SEXP _xopt_probe_xad_xtensor() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(probe_xad_xtensor());
    return rcpp_result_gen;
END_RCPP
}
// test_rosenbrock_benchmark
int test_rosenbrock_benchmark();
RcppExport SEXP _xopt_test_rosenbrock_benchmark() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_rosenbrock_benchmark());
    return rcpp_result_gen;
END_RCPP
}
// test_sphere_benchmark
int test_sphere_benchmark();
RcppExport SEXP _xopt_test_sphere_benchmark() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_sphere_benchmark());
    return rcpp_result_gen;
END_RCPP
}
// test_powell_singular_benchmark
int test_powell_singular_benchmark();
RcppExport SEXP _xopt_test_powell_singular_benchmark() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_powell_singular_benchmark());
    return rcpp_result_gen;
END_RCPP
}
// test_beale_benchmark
int test_beale_benchmark();
RcppExport SEXP _xopt_test_beale_benchmark() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_beale_benchmark());
    return rcpp_result_gen;
END_RCPP
}
// test_brown_badly_scaled_benchmark
int test_brown_badly_scaled_benchmark();
RcppExport SEXP _xopt_test_brown_badly_scaled_benchmark() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_brown_badly_scaled_benchmark());
    return rcpp_result_gen;
END_RCPP
}
// test_broyden_tridiagonal_benchmark
int test_broyden_tridiagonal_benchmark();
RcppExport SEXP _xopt_test_broyden_tridiagonal_benchmark() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_broyden_tridiagonal_benchmark());
    return rcpp_result_gen;
END_RCPP
}
// test_quadratic_benchmark
int test_quadratic_benchmark();
RcppExport SEXP _xopt_test_quadratic_benchmark() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_quadratic_benchmark());
    return rcpp_result_gen;
END_RCPP
}
// xopt_chol_impl
Rcpp::NumericMatrix xopt_chol_impl(Rcpp::NumericMatrix A);
RcppExport SEXP _xopt_xopt_chol_impl(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_chol_impl(A));
    return rcpp_result_gen;
END_RCPP
}
// xopt_solve_impl
Rcpp::NumericVector xopt_solve_impl(Rcpp::NumericMatrix A, Rcpp::NumericVector b);
RcppExport SEXP _xopt_xopt_solve_impl(SEXP ASEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_solve_impl(A, b));
    return rcpp_result_gen;
END_RCPP
}
// xopt_logdet_impl
double xopt_logdet_impl(Rcpp::NumericMatrix A);
RcppExport SEXP _xopt_xopt_logdet_impl(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_logdet_impl(A));
    return rcpp_result_gen;
END_RCPP
}
// xopt_inv_impl
Rcpp::NumericMatrix xopt_inv_impl(Rcpp::NumericMatrix A);
RcppExport SEXP _xopt_xopt_inv_impl(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_inv_impl(A));
    return rcpp_result_gen;
END_RCPP
}
// xopt_chol_grad
Rcpp::NumericMatrix xopt_chol_grad(Rcpp::NumericMatrix A);
RcppExport SEXP _xopt_xopt_chol_grad(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_chol_grad(A));
    return rcpp_result_gen;
END_RCPP
}
// xopt_solve_grad
SEXP xopt_solve_grad(Rcpp::NumericMatrix A, Rcpp::NumericVector b, std::string wrt);
RcppExport SEXP _xopt_xopt_solve_grad(SEXP ASEXP, SEXP bSEXP, SEXP wrtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< std::string >::type wrt(wrtSEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_solve_grad(A, b, wrt));
    return rcpp_result_gen;
END_RCPP
}
// xopt_logdet_grad
Rcpp::NumericMatrix xopt_logdet_grad(Rcpp::NumericMatrix A);
RcppExport SEXP _xopt_xopt_logdet_grad(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_logdet_grad(A));
    return rcpp_result_gen;
END_RCPP
}
// xopt_inv_grad
Rcpp::NumericMatrix xopt_inv_grad(Rcpp::NumericMatrix A);
RcppExport SEXP _xopt_xopt_inv_grad(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_inv_grad(A));
    return rcpp_result_gen;
END_RCPP
}
// xopt_linalg_tape_bytes
double xopt_linalg_tape_bytes(Rcpp::NumericMatrix A, std::string op);
RcppExport SEXP _xopt_xopt_linalg_tape_bytes(SEXP ASEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< std::string >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(xopt_linalg_tape_bytes(A, op));
    return rcpp_result_gen;
END_RCPP
}
// test_multistart_rosenbrock
int test_multistart_rosenbrock();
RcppExport SEXP _xopt_test_multistart_rosenbrock() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_multistart_rosenbrock());
    return rcpp_result_gen;
END_RCPP
}
// test_multistart_rastrigin
int test_multistart_rastrigin();
RcppExport SEXP _xopt_test_multistart_rastrigin() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_multistart_rastrigin());
    return rcpp_result_gen;
END_RCPP
}
// test_multistart_deterministic
int test_multistart_deterministic();
RcppExport SEXP _xopt_test_multistart_deterministic() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_multistart_deterministic());
    return rcpp_result_gen;
END_RCPP
}
// test_multistart_scaling
int test_multistart_scaling();
RcppExport SEXP _xopt_test_multistart_scaling() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_multistart_scaling());
    return rcpp_result_gen;
END_RCPP
}
// test_nls_exponential_decay
int test_nls_exponential_decay();
RcppExport SEXP _xopt_test_nls_exponential_decay() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_nls_exponential_decay());
    return rcpp_result_gen;
END_RCPP
}
// test_nls_misra1a
int test_nls_misra1a();
RcppExport SEXP _xopt_test_nls_misra1a() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_nls_misra1a());
    return rcpp_result_gen;
END_RCPP
}
// test_nls_linear
int test_nls_linear();
RcppExport SEXP _xopt_test_nls_linear() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_nls_linear());
    return rcpp_result_gen;
END_RCPP
}
// test_nls_jacobian_accuracy
int test_nls_jacobian_accuracy();
RcppExport SEXP _xopt_test_nls_jacobian_accuracy() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_nls_jacobian_accuracy());
    return rcpp_result_gen;
END_RCPP
}
// test_nls_covariance
int test_nls_covariance();
RcppExport SEXP _xopt_test_nls_covariance() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_nls_covariance());
    return rcpp_result_gen;
END_RCPP
}
// test_nls_osborne1
int test_nls_osborne1();
RcppExport SEXP _xopt_test_nls_osborne1() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_nls_osborne1());
    return rcpp_result_gen;
END_RCPP
}
// test_nls_helical_valley
int test_nls_helical_valley();
RcppExport SEXP _xopt_test_nls_helical_valley() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_nls_helical_valley());
    return rcpp_result_gen;
END_RCPP
}
// test_nls_performance
int test_nls_performance();
RcppExport SEXP _xopt_test_nls_performance() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_nls_performance());
    return rcpp_result_gen;
END_RCPP
}
// test_param_spec_roundtrip
int test_param_spec_roundtrip();
RcppExport SEXP _xopt_test_param_spec_roundtrip() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_param_spec_roundtrip());
    return rcpp_result_gen;
END_RCPP
}
// test_positive_transform
int test_positive_transform();
RcppExport SEXP _xopt_test_positive_transform() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_positive_transform());
    return rcpp_result_gen;
END_RCPP
}
// test_bounded_transform
int test_bounded_transform();
RcppExport SEXP _xopt_test_bounded_transform() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_bounded_transform());
    return rcpp_result_gen;
END_RCPP
}
// test_rosenbrock_structured
int test_rosenbrock_structured();
RcppExport SEXP _xopt_test_rosenbrock_structured() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_rosenbrock_structured());
    return rcpp_result_gen;
END_RCPP
}
// test_positive_constrained_mle
int test_positive_constrained_mle();
RcppExport SEXP _xopt_test_positive_constrained_mle() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_positive_constrained_mle());
    return rcpp_result_gen;
END_RCPP
}
// test_phase3_hessian_hvp
int test_phase3_hessian_hvp();
RcppExport SEXP _xopt_test_phase3_hessian_hvp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_phase3_hessian_hvp());
    return rcpp_result_gen;
END_RCPP
}
// test_phase3_trust_region_newton
int test_phase3_trust_region_newton();
RcppExport SEXP _xopt_test_phase3_trust_region_newton() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_phase3_trust_region_newton());
    return rcpp_result_gen;
END_RCPP
}
// test_phase3_laplace
int test_phase3_laplace();
RcppExport SEXP _xopt_test_phase3_laplace() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_phase3_laplace());
    return rcpp_result_gen;
END_RCPP
}
// test_phase4_constraints
int test_phase4_constraints();
RcppExport SEXP _xopt_test_phase4_constraints() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_phase4_constraints());
    return rcpp_result_gen;
END_RCPP
}
// test_phase4_multistart_parallel
int test_phase4_multistart_parallel();
RcppExport SEXP _xopt_test_phase4_multistart_parallel() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_phase4_multistart_parallel());
    return rcpp_result_gen;
END_RCPP
}
// test_phase4_sparse
int test_phase4_sparse();
RcppExport SEXP _xopt_test_phase4_sparse() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_phase4_sparse());
    return rcpp_result_gen;
END_RCPP
}
// test_phase4_jit_checkpoint
int test_phase4_jit_checkpoint();
RcppExport SEXP _xopt_test_phase4_jit_checkpoint() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_phase4_jit_checkpoint());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_xopt_probe_xad_xtensor", (DL_FUNC) &_xopt_probe_xad_xtensor, 0},
    {"_xopt_test_rosenbrock_benchmark", (DL_FUNC) &_xopt_test_rosenbrock_benchmark, 0},
    {"_xopt_test_sphere_benchmark", (DL_FUNC) &_xopt_test_sphere_benchmark, 0},
    {"_xopt_test_powell_singular_benchmark", (DL_FUNC) &_xopt_test_powell_singular_benchmark, 0},
    {"_xopt_test_beale_benchmark", (DL_FUNC) &_xopt_test_beale_benchmark, 0},
    {"_xopt_test_brown_badly_scaled_benchmark", (DL_FUNC) &_xopt_test_brown_badly_scaled_benchmark, 0},
    {"_xopt_test_broyden_tridiagonal_benchmark", (DL_FUNC) &_xopt_test_broyden_tridiagonal_benchmark, 0},
    {"_xopt_test_quadratic_benchmark", (DL_FUNC) &_xopt_test_quadratic_benchmark, 0},
    {"_xopt_xopt_chol_impl", (DL_FUNC) &_xopt_xopt_chol_impl, 1},
    {"_xopt_xopt_solve_impl", (DL_FUNC) &_xopt_xopt_solve_impl, 2},
    {"_xopt_xopt_logdet_impl", (DL_FUNC) &_xopt_xopt_logdet_impl, 1},
    {"_xopt_xopt_inv_impl", (DL_FUNC) &_xopt_xopt_inv_impl, 1},
    {"_xopt_xopt_chol_grad", (DL_FUNC) &_xopt_xopt_chol_grad, 1},
    {"_xopt_xopt_solve_grad", (DL_FUNC) &_xopt_xopt_solve_grad, 3},
    {"_xopt_xopt_logdet_grad", (DL_FUNC) &_xopt_xopt_logdet_grad, 1},
    {"_xopt_xopt_inv_grad", (DL_FUNC) &_xopt_xopt_inv_grad, 1},
    {"_xopt_xopt_linalg_tape_bytes", (DL_FUNC) &_xopt_xopt_linalg_tape_bytes, 2},
    {"_xopt_test_multistart_rosenbrock", (DL_FUNC) &_xopt_test_multistart_rosenbrock, 0},
    {"_xopt_test_multistart_rastrigin", (DL_FUNC) &_xopt_test_multistart_rastrigin, 0},
    {"_xopt_test_multistart_deterministic", (DL_FUNC) &_xopt_test_multistart_deterministic, 0},
    {"_xopt_test_multistart_scaling", (DL_FUNC) &_xopt_test_multistart_scaling, 0},
    {"_xopt_test_nls_exponential_decay", (DL_FUNC) &_xopt_test_nls_exponential_decay, 0},
    {"_xopt_test_nls_misra1a", (DL_FUNC) &_xopt_test_nls_misra1a, 0},
    {"_xopt_test_nls_linear", (DL_FUNC) &_xopt_test_nls_linear, 0},
    {"_xopt_test_nls_jacobian_accuracy", (DL_FUNC) &_xopt_test_nls_jacobian_accuracy, 0},
    {"_xopt_test_nls_covariance", (DL_FUNC) &_xopt_test_nls_covariance, 0},
    {"_xopt_test_nls_osborne1", (DL_FUNC) &_xopt_test_nls_osborne1, 0},
    {"_xopt_test_nls_helical_valley", (DL_FUNC) &_xopt_test_nls_helical_valley, 0},
    {"_xopt_test_nls_performance", (DL_FUNC) &_xopt_test_nls_performance, 0},
    {"_xopt_test_param_spec_roundtrip", (DL_FUNC) &_xopt_test_param_spec_roundtrip, 0},
    {"_xopt_test_positive_transform", (DL_FUNC) &_xopt_test_positive_transform, 0},
    {"_xopt_test_bounded_transform", (DL_FUNC) &_xopt_test_bounded_transform, 0},
    {"_xopt_test_rosenbrock_structured", (DL_FUNC) &_xopt_test_rosenbrock_structured, 0},
    {"_xopt_test_positive_constrained_mle", (DL_FUNC) &_xopt_test_positive_constrained_mle, 0},
    {"_xopt_test_phase3_hessian_hvp", (DL_FUNC) &_xopt_test_phase3_hessian_hvp, 0},
    {"_xopt_test_phase3_trust_region_newton", (DL_FUNC) &_xopt_test_phase3_trust_region_newton, 0},
    {"_xopt_test_phase3_laplace", (DL_FUNC) &_xopt_test_phase3_laplace, 0},
    {"_xopt_test_phase4_constraints", (DL_FUNC) &_xopt_test_phase4_constraints, 0},
    {"_xopt_test_phase4_multistart_parallel", (DL_FUNC) &_xopt_test_phase4_multistart_parallel, 0},
    {"_xopt_test_phase4_sparse", (DL_FUNC) &_xopt_test_phase4_sparse, 0},
    {"_xopt_test_phase4_jit_checkpoint", (DL_FUNC) &_xopt_test_phase4_jit_checkpoint, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_xopt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
