# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

probe_xad_xtensor <- function() {
    .Call('_xopt_probe_xad_xtensor', PACKAGE = 'xopt')
}

probe_sdm <- function() {
    .Call('_xopt_probe_sdm', PACKAGE = 'xopt')
}
