# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

probe_xad_xtensor <- function() {
    .Call('_xopt_probe_xad_xtensor', PACKAGE = 'xopt')
}

probe_sdm <- function() {
    .Call('_xopt_probe_sdm', PACKAGE = 'xopt')
}

test_logistic_sdm_gradient <- function() {
    .Call('_xopt_test_logistic_sdm_gradient', PACKAGE = 'xopt')
}

test_logistic_sdm_endtoend <- function() {
    .Call('_xopt_test_logistic_sdm_endtoend', PACKAGE = 'xopt')
}

test_masked_sum <- function() {
    .Call('_xopt_test_masked_sum', PACKAGE = 'xopt')
}

test_raster_mask_na <- function() {
    .Call('_xopt_test_raster_mask_na', PACKAGE = 'xopt')
}

test_logistic_sdm_with_na <- function() {
    .Call('_xopt_test_logistic_sdm_with_na', PACKAGE = 'xopt')
}

test_mask_intersection <- function() {
    .Call('_xopt_test_mask_intersection', PACKAGE = 'xopt')
}

test_rosenbrock_benchmark <- function() {
    .Call('_xopt_test_rosenbrock_benchmark', PACKAGE = 'xopt')
}

test_sphere_benchmark <- function() {
    .Call('_xopt_test_sphere_benchmark', PACKAGE = 'xopt')
}

test_powell_singular_benchmark <- function() {
    .Call('_xopt_test_powell_singular_benchmark', PACKAGE = 'xopt')
}

test_beale_benchmark <- function() {
    .Call('_xopt_test_beale_benchmark', PACKAGE = 'xopt')
}

test_brown_badly_scaled_benchmark <- function() {
    .Call('_xopt_test_brown_badly_scaled_benchmark', PACKAGE = 'xopt')
}

test_broyden_tridiagonal_benchmark <- function() {
    .Call('_xopt_test_broyden_tridiagonal_benchmark', PACKAGE = 'xopt')
}

test_quadratic_benchmark <- function() {
    .Call('_xopt_test_quadratic_benchmark', PACKAGE = 'xopt')
}

test_param_spec_roundtrip <- function() {
    .Call('_xopt_test_param_spec_roundtrip', PACKAGE = 'xopt')
}

test_positive_transform <- function() {
    .Call('_xopt_test_positive_transform', PACKAGE = 'xopt')
}

test_bounded_transform <- function() {
    .Call('_xopt_test_bounded_transform', PACKAGE = 'xopt')
}

test_rosenbrock_structured <- function() {
    .Call('_xopt_test_rosenbrock_structured', PACKAGE = 'xopt')
}

test_positive_constrained_mle <- function() {
    .Call('_xopt_test_positive_constrained_mle', PACKAGE = 'xopt')
}

test_nls_exponential_decay <- function() {
    .Call('_xopt_test_nls_exponential_decay', PACKAGE = 'xopt')
}

test_nls_misra1a <- function() {
    .Call('_xopt_test_nls_misra1a', PACKAGE = 'xopt')
}

test_nls_linear <- function() {
    .Call('_xopt_test_nls_linear', PACKAGE = 'xopt')
}

test_nls_jacobian_accuracy <- function() {
    .Call('_xopt_test_nls_jacobian_accuracy', PACKAGE = 'xopt')
}

test_nls_covariance <- function() {
    .Call('_xopt_test_nls_covariance', PACKAGE = 'xopt')
}

test_multistart_rosenbrock <- function() {
    .Call('_xopt_test_multistart_rosenbrock', PACKAGE = 'xopt')
}

test_multistart_rastrigin <- function() {
    .Call('_xopt_test_multistart_rastrigin', PACKAGE = 'xopt')
}

test_multistart_deterministic <- function() {
    .Call('_xopt_test_multistart_deterministic', PACKAGE = 'xopt')
}

test_multistart_scaling <- function() {
    .Call('_xopt_test_multistart_scaling', PACKAGE = 'xopt')
}
