# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

<<<<<<< HEAD
#' @title Probe SDM optimization
#' @description Test optimization for species distribution modeling use case
#' @export
probe_sdm <- function() {
    .Call(`_xopt_probe_sdm`)
}

#' @title Probe XAD and xtensor integration
#' @description Test that automatic differentiation works with tensor inputs
#' @export
probe_xad_xtensor <- function() {
    .Call(`_xopt_probe_xad_xtensor`)
=======
probe_xad_xtensor <- function() {
    .Call('_xopt_probe_xad_xtensor', PACKAGE = 'xopt')
>>>>>>> b2d690ef57a88db16177941af7f21b10f327cbf9
}

test_rosenbrock_benchmark <- function() {
    .Call(`_xopt_test_rosenbrock_benchmark`)
}

test_sphere_benchmark <- function() {
    .Call(`_xopt_test_sphere_benchmark`)
}

test_powell_singular_benchmark <- function() {
    .Call(`_xopt_test_powell_singular_benchmark`)
}

test_beale_benchmark <- function() {
    .Call(`_xopt_test_beale_benchmark`)
}

test_brown_badly_scaled_benchmark <- function() {
    .Call(`_xopt_test_brown_badly_scaled_benchmark`)
}

test_broyden_tridiagonal_benchmark <- function() {
    .Call(`_xopt_test_broyden_tridiagonal_benchmark`)
}

test_quadratic_benchmark <- function() {
    .Call(`_xopt_test_quadratic_benchmark`)
}

#' @title Test logistic SDM gradient accuracy
#' @description Numerical gradient check for small raster stack
#' @export
test_logistic_sdm_gradient <- function() {
    .Call(`_xopt_test_logistic_sdm_gradient`)
}

#' @title Test logistic SDM end-to-end
#' @description Full test of model value, gradient, and predictions
#' @export
test_logistic_sdm_endtoend <- function() {
    .Call(`_xopt_test_logistic_sdm_endtoend`)
}

#' @title Test masked sum reduction
#' @description Test sum_masked function with various masks
#' @export
test_masked_sum <- function() {
    .Call(`_xopt_test_masked_sum`)
}

#' @title Test raster mask from NA values
#' @description Test automatic mask creation from NA-containing data
#' @export
test_raster_mask_na <- function() {
    .Call(`_xopt_test_raster_mask_na`)
}

#' @title Test logistic SDM with NA values
#' @description Test that logistic SDM handles NA values correctly
#' @export
test_logistic_sdm_with_na <- function() {
    .Call(`_xopt_test_logistic_sdm_with_na`)
}

#' @title Test mask intersection
#' @description Test combining multiple masks
#' @export
test_mask_intersection <- function() {
    .Call(`_xopt_test_mask_intersection`)
}

test_multistart_rosenbrock <- function() {
    .Call(`_xopt_test_multistart_rosenbrock`)
}

test_multistart_rastrigin <- function() {
    .Call(`_xopt_test_multistart_rastrigin`)
}

test_multistart_deterministic <- function() {
    .Call(`_xopt_test_multistart_deterministic`)
}

test_multistart_scaling <- function() {
    .Call(`_xopt_test_multistart_scaling`)
}

test_nls_exponential_decay <- function() {
    .Call(`_xopt_test_nls_exponential_decay`)
}

test_nls_misra1a <- function() {
    .Call(`_xopt_test_nls_misra1a`)
}

test_nls_linear <- function() {
    .Call(`_xopt_test_nls_linear`)
}

test_nls_jacobian_accuracy <- function() {
    .Call(`_xopt_test_nls_jacobian_accuracy`)
}

test_nls_covariance <- function() {
    .Call(`_xopt_test_nls_covariance`)
}

test_nls_osborne1 <- function() {
    .Call(`_xopt_test_nls_osborne1`)
}

test_nls_helical_valley <- function() {
    .Call(`_xopt_test_nls_helical_valley`)
}

test_nls_performance <- function() {
    .Call(`_xopt_test_nls_performance`)
}

test_param_spec_roundtrip <- function() {
    .Call(`_xopt_test_param_spec_roundtrip`)
}

test_positive_transform <- function() {
    .Call(`_xopt_test_positive_transform`)
}

test_bounded_transform <- function() {
    .Call(`_xopt_test_bounded_transform`)
}

test_rosenbrock_structured <- function() {
    .Call(`_xopt_test_rosenbrock_structured`)
}

test_positive_constrained_mle <- function() {
    .Call(`_xopt_test_positive_constrained_mle`)
}

test_phase3_hessian_hvp <- function() {
    .Call(`_xopt_test_phase3_hessian_hvp`)
}

test_phase3_trust_region_newton <- function() {
    .Call(`_xopt_test_phase3_trust_region_newton`)
}

test_phase3_laplace <- function() {
    .Call(`_xopt_test_phase3_laplace`)
}

test_phase4_constraints <- function() {
    .Call(`_xopt_test_phase4_constraints`)
}

test_phase4_multistart_parallel <- function() {
    .Call(`_xopt_test_phase4_multistart_parallel`)
}

test_phase4_sparse <- function() {
    .Call(`_xopt_test_phase4_sparse`)
}

test_phase4_jit_checkpoint <- function() {
    .Call(`_xopt_test_phase4_jit_checkpoint`)
}

